### ISSUE TITLE
Make upload file constraints more clearly

### ISSUE THREAD

**Issue by icoxfog417** [doccano/doccano#521]
Users are confused about some upload file constraints. So we have to make it clear on manual or error message.

- [ ] #485: trailing of spaces
- [ ] #511 / #514 : file size limit (maybe memory issue)
- [ ] #512 : update of error message
- [ ] #516 : does not accept data without label

**Comment by kuraga** [comment]
@icoxfog417 Thanks! Could you add "use API's error message in UI"? Because even we have #157 after #150, I see [common message](https://github.com/doccano/doccano/pull/157#issuecomment-568939659) only.

**Comment by kuraga** [comment]
@icoxfog417, could you, please, add to the list above:
* "use API's error message in UI": even after #157 I see [common message](https://github.com/doccano/doccano/pull/157#issuecomment-568939659) only.
* #601 issue.
Thanks!

**Comment by icoxfog417** [comment]
These issues are already linked to this issue by your comment so enough to manage.
