### ISSUE TITLE
Known issue about Annotation UI

### ISSUE THREAD

**Issue by icoxfog417** [doccano/doccano#880]
**Please read this issue when you faced the problem of annotation user interface.**  
**If you faced the following issue, please upvote 👍 related issue that let us judge priority.**

* Display
  * [x] Nonworking delete button is shown for labels of other users #866
  * [x] Feature Request: Keep and Display the new line in the Text Classification Task #879
  * [x] RTL language Support #769
  * [x] Can't change from "Checked" to "Not Checked"? #481
* Filter
  * [x] Done / Undone filter does not work correctly #808
  * [x] After filtering the dataset when clicking the annotation it is not shown the proper data (from the filter) #765
  * [x] Choosing filter twice results in 404 error #754
  * [x] The display of the document index does not change after filtering #594
* Pagination
  - [x] Pagination unresponsive for large documents #873 
  - [x] Execute refresh above the pagination-boundary example causes miss ordering #804 
* File upload
  - [x] Make upload file constraints more clearly #521
  - [x] [Enhancement request] Allow to import unlabeled datasets #658
  - [x]  Unable to import CoNLL files #1046

**Comment by br-dr3** [comment]
Maybe #804 had been solved by #850

**Comment by jeroavf** [comment]
Hi 
#873 is probably associated with the problem I am facing . When using a dataset of approximately 10 MB , the search function ,when annotating, is extremely slow. I think it's due to for every character you type it refreshes the search result. I suggest to include a button to start the search after the user completed typing the string to be searched.

**Comment by Jian1273** [comment]
What is the save path of the dataset uploaded via pip installation

**Comment by tracyhenry** [comment]
Hi

Related to #521 - if something I upload is not well-formatted (e.g. a JSON file with single quotes instead of double quotes), I'd see nothing after hitting the `ingest` button. I only get to know that the upload fails if I look at the celery log. An immediate improvement could be showing an alert somewhere.
