### ISSUE TITLE
Improvement Idea for doccano

### ISSUE THREAD

**Issue by icoxfog417** [doccano/doccano#882]
**Please read this issue when you want to add the feature to doccano**  
**Please upvote 👍 related issue that let us judge priority .**

## Toward More Practical Annotation Tool

* Dataset
  - [ ]: Feature Request: Bulk Delete #523
  - [ ]: Convert label to label-ID when exporting #295
  - [ ]: Feature Request: support HTML syntax in content #35
  - [ ]: Feature Request: Import the exported annotation data and keep the all original info #482
  - [ ]: Feature Request: Support JSON format (not JSONL) #454
* Filter
  - [ ]: Clarify document's annotation status and filter by it. #280
  - [ ]: [Enhancement request] "First" and "Last" buttons #615
* Annotation
  - [ ]: [Feature request] Provide for setting the order of labels #816
  - [ ]: Group labels by the same color #477
  - [ ]: [Enhancement request] Display shortkey in labels selector (on Annotation page) #834
  - [ ]: feature request: keyboard shortcut for approval button #718
  - [ ]: A button to clear the markup. #631
  - [ ]: Automatically select the sequential characters in the sequence labeling task by the hover. #666
  - [ ]: Feature Request: Show context when annotation. #466
* Navigation
  - [ ]: Redirect to the specific page by id, not by offset. #540
* Project Management
  - [ ]: [Feature Request] Allowed to add more metadata for a project #687
  - [ ]: Feature Request: Restore the deleted project #571
* Productivity
  - [ ]: Display the who annotated the document #881
  - [ ]: Enable Stats view for non-admins #270

## Toward Production Usage

* Deployment
  - [ ]: Helm chart #701
  - [ ]: Support doccano v1.x on Heroku #811
* Security
  - [ ] :  [Proposal] Warn and/or fail if default admin's password hasn't been changed #857
  - [ ]: Clarify how to set user own username/password in docker-compose for security #748
* Authentication
  - [ ]: Two factor authentication for admin and annotators #756
  - [ ]: Add Okta Integration for OAuth #674
  - [ ]: Google OAuth support #620
  - [ ]: LDAP-Support #560
* Annotation Workflow
  - [ ]: Allow user to change another users' annotation #531
* Annotator Management
  - [ ]: Allow to assign more than one role in a project. #537
  - [ ]: Enhance Statistics: Compare Annotators #114
* Accessibility
  - [ ]: Multiple language interface #479

**Comment by kuraga** [comment]
Has been closed but not listed here:

- Annotations out of order when exporting #875
- Keep and Display the new line in the Text Classification Task #879
- Use color in labels selector (on Annotation page) #829
- Reflect opacity in Color column (on Labels page) #814
- Use color in labels selector (on Annotation page) #829
- Using more descriptive error messages in UI #739
- Put label hints and key shortcut hints back to Annotation page #635
- Localize roles in UI #605
- Enable resize of information pane #501
- Allow for partial export of dataset #871
- Implement a control of annotation coverage per document #831 
- Make annotation screen CSS customizable #688
- Implement "Approved" filter #725

**Comment by kuraga** [comment]
Also I have a similar list: #515.

P.S. I hope, :+1:s above will be refreshed from time to time.

**Comment by setu4993** [comment]
@icoxfog417 : #674 can be resolved by my open PR #675.

**Comment by kuraga** [comment]
Ask to reopen #739 as it's a bug report instead of feature request.

**Comment by jeroavf** [comment]
My proposal :
When using a dataset of approximately 10 MB , the search function is extremely slow. I think it's due to every character you type it refreshes the search result. I suggest to include a button to start the search only after the user completed typing the string to be searched.

**Comment by br-dr3** [comment]
@icoxfog417 why #708 isn't here?

**Comment by nbroad1881** [comment]
What about snapping to word boundaries when highlighting? Currently, users can highlight the middle of words or they can miss a character or two if they aren't careful.  Maybe a toggle switch in-case there are instances where it isn't desirable.

I'm basically just trying to get doccano to be more like [prodigy](https://prodi.gy/demo)

**Comment by ljades** [comment]
Do roadmap-announced features get added to this list? Getting a plugin feature for defining custom tasks would be fantastic and would make our team much more ready to adopt.

**Comment by GitOffice** [comment]
Why not show directly all the labels on the top of sequence labelling window like the old UI?

**Comment by ljades** [comment]
Can we get the new frontend to include all the social auth options? Okta and OIDC integration are in the backend, which is a great thing, but the new frontend still does not have them. https://github.com/doccano/doccano/issues/1255

**Comment by Vydruth** [comment]
@Hironsan and @icoxfog417 can we replace #674 with https://github.com/doccano/doccano/issues/1255  in the first comment? I see quite a bit of people asking for this feature? Can this be prioritized, please. Since authentication is like the basic thing that everyone will need.

**Comment by RaghuThota** [comment]
Yeah. I agree with @Vydruth

**Comment by Hironsan** [comment]
If someone sends the Pull Request about authentication, I would accept it.

**Comment by Vydruth** [comment]
On the new UI, I see that there is no way `For users to be able to Create a New Account`, although there is a workaround for this (admin creates an account for the user and provide them with username and password.) it will not work due to security concerns, as another important feature `For users to be able to change his/her password.` is missing.
